<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('courses')->delete();
        
        \DB::table('courses')->insert(array (
            0 => 
            array (
                'id' => '3',
                'uuid' => '068ffef5-8f4f-4a1c-8db3-3d5c3aa41031',
                'workspace_id' => '1',
                'admin_id' => '1',
                'category_id' => '6',
                'price' => '15000.00',
                'price_monthly' => NULL,
                'price_yearly' => NULL,
                'price_two_years' => NULL,
                'price_three_years' => NULL,
                'deadline' => '2022-09-27',
                'outcomes' => '["Somo hili linalenga kumjengea raia tabia inayokubalika ya kuheshimu na kuthamini jamii pamoja na kuwa na itikadi tofauti.","Tutajifunza umuhimu wa ustahimilivu, uadilifu pamoja na kudumisha amani;"]',
                'language' => NULL,
                'summary' => '<p>Hili somo rasmi la Uraia na Maadili ni somo kwa kila mtanzania wa umri wowote na linahusu hasa kanuni zinazobainisha uzuri na ubaya wa matendo ya binadamu. Tutajifunza ni jinsi gani binadamu anastahili au anapaswa kuishi. Kwa maneno mengine, katika Somo la Uraia na Maadili tunajiuliza maisha mazuri ni yapi? Kuishi vizuri maana yake ni nini? Ubaya ni nini? Tunawezaje kuishi kama binadamu?</p>',
                'duration' => '3',
                'name' => 'URAIA, MAADILI NA SHERIA ZA MSINGI NA SHERIA ZA ARDHI',
                'description' => '<p>Hili somo rasmi la Uraia na Maadili ni somo kwa kila mtanzania wa umri wowote na linahusu hasa kanuni zinazobainisha uzuri na ubaya wa matendo ya binadamu. Tutajifunza ni jinsi gani binadamu anastahili au anapaswa kuishi. Kwa maneno mengine, katika Somo la Uraia na Maadili tunajiuliza maisha mazuri ni yapi? Kuishi vizuri maana yake ni nini? Ubaya ni nini? Tunawezaje kuishi kama binadamu?</p>',
                'image' => 'media/bKVLch6y1LySPjbPvzR4RLPod3Buvjl6EAxARgRi.png',
                'video' => NULL,
                'certificate' => 'Yes',
                'status' => 'Published',
                'level' => 'Beginner',
                'created_at' => '2022-09-27 08:40:30',
                'updated_at' => '2022-09-27 13:55:20',
                'slug' => 'uraia,-maadili-na-sheria-za-msingi-na-sheria-za-ardhi',
            ),
            1 => 
            array (
                'id' => '4',
                'uuid' => 'ac94e640-eda7-4628-bc97-b81114f8d04c',
                'workspace_id' => '1',
                'admin_id' => '1',
                'category_id' => '4',
                'price' => '15000.00',
                'price_monthly' => NULL,
                'price_yearly' => NULL,
                'price_two_years' => NULL,
                'price_three_years' => NULL,
                'deadline' => '2022-09-27',
                'outcomes' => '["Moduli hii itaongeza chachu kubwa katika kutambua zaidi baraza na kujenga uhalisi kuliko upotoshaji ambao umevizwa kwa muda mrefu na watu."]',
                'language' => NULL,
                'summary' => '<p>Moduli hii ni maalumu kwa viongozi ambao wapo katika nafasi mbali mbali za BAKWATA kwa sasa na wale ambao si viongozi lakini wangependa kusoma kwa matumizi yao ya baadaye. </p>',
                'duration' => '3',
                'name' => 'UONGOZI NDANI YA BAKWATA',
                'description' => '<p>Moduli hii ni maalumu kwa viongozi ambao wapo katika nafasi mbali mbali za BAKWATA kwa sasa na wale ambao si viongozi lakini wangependa kusoma kwa matumizi yao ya baadaye. </p>',
                'image' => 'media/FRQ7U02FP5PHVDzLfHP84ZM0rNskoz7yCNJXro4z.png',
                'video' => NULL,
                'certificate' => 'Yes',
                'status' => 'Published',
                'level' => 'Beginner',
                'created_at' => '2022-09-27 09:40:10',
                'updated_at' => '2022-09-27 13:53:22',
                'slug' => 'uongozi-ndani-ya-bakwata',
            ),
            2 => 
            array (
                'id' => '5',
                'uuid' => '6fb1ff13-21cf-4628-aa12-0da9704241ed',
                'workspace_id' => '1',
                'admin_id' => '1',
                'category_id' => '4',
                'price' => '20000.00',
                'price_monthly' => NULL,
                'price_yearly' => NULL,
                'price_two_years' => NULL,
                'price_three_years' => NULL,
                'deadline' => '2022-09-27',
                'outcomes' => '["Ni muhimu Imam kushirikiana na viongozi walioko chini yake kama katibu, mweka hazina na wajumbe ili kusimamia msikiti na kuendesha shughuli za kiimani na kimaendeleo za msikiti husika."]',
                'language' => NULL,
                'summary' => '<p>Kozi hii ni maalum kwa Viongozi wa Msikiti kama imam, Katibu, Mweka hazina na Wajumbe wote na pia ni hiari kwa yoyote anayehitaji maarifa na kujiandaa kuongoza msikiti siku zijazo katika maisha yake.</p>',
                'duration' => '1',
                'name' => 'UONGOZI NA USIMAMIZI WA MSIKITI',
                'description' => '<p>Kozi hii ni maalum kwa Viongozi wa Msikiti kama imam, Katibu, Mweka hazina na Wajumbe wote na pia ni hiari kwa yoyote anayehitaji maarifa na kujiandaa kuongoza msikiti siku zijazo katika maisha yake.</p>',
                'image' => 'media/S5qKM9heZzSNbfPm1oAunVwEnk0LCYVEfEnIMXRz.png',
                'video' => NULL,
                'certificate' => 'Yes',
                'status' => 'Published',
                'level' => 'Beginner',
                'created_at' => '2022-09-27 09:53:11',
                'updated_at' => '2022-09-27 13:52:54',
                'slug' => 'uongozi-na-usimamizi-wa-msikiti',
            ),
            3 => 
            array (
                'id' => '6',
                'uuid' => '48e0b93f-478a-4da9-87c6-ea09c10c2cd3',
                'workspace_id' => '1',
                'admin_id' => '1',
                'category_id' => '3',
                'price' => '10000.00',
                'price_monthly' => NULL,
                'price_yearly' => NULL,
                'price_two_years' => NULL,
                'price_three_years' => NULL,
                'deadline' => '2022-09-27',
                'outcomes' => '["Mbinu muhimu za\\tufugaji wa kuku kwa faida ikizingatiwa kufuga\\tkwa\\tkanuni za kisasa na maradhi ya kuku\\tbila\\tkusahau\\ttiba\\tza maradhi hayo."]',
                'language' => NULL,
                'summary' => '<p>Kitabu hiki kitaelekeza kwa muhtasari mbinu muhimu za ufugaji wa kuku kwa faida ikizingatiwa kufuga kwa kanuni za kisasa na maradhi ya kuku bila kusahau tiba za maradhi hayo ili mfugaji haweze kupata faida inayoendana na juhudi zake bila kusahau mtaji aliyotumia katika mradi wa kuku.</p>',
                'duration' => '3',
                'name' => 'UFUGAJI WA KUKU',
                'description' => '<p>Kitabu hiki kitaelekeza kwa muhtasari mbinu muhimu za ufugaji wa kuku kwa faida ikizingatiwa kufuga kwa kanuni za kisasa na maradhi ya kuku bila kusahau tiba za maradhi hayo ili mfugaji haweze kupata faida inayoendana na juhudi zake bila kusahau mtaji aliyotumia katika mradi wa kuku.</p>',
                'image' => 'media/HflOkb3YMV8tXy7pHNWTCYJen8GwsGhIb8v0xGqg.png',
                'video' => NULL,
                'certificate' => 'Yes',
                'status' => 'Published',
                'level' => 'Beginner',
                'created_at' => '2022-09-27 10:04:47',
                'updated_at' => '2022-09-27 13:51:40',
                'slug' => 'ufugaji-wa-kuku',
            ),
            4 => 
            array (
                'id' => '7',
                'uuid' => '394c1adc-d124-44d7-ac98-dc99c3f48b96',
                'workspace_id' => '1',
                'admin_id' => '1',
                'category_id' => '3',
                'price' => '20000.00',
                'price_monthly' => NULL,
                'price_yearly' => NULL,
                'price_two_years' => NULL,
                'price_three_years' => NULL,
                'deadline' => '2022-09-27',
                'outcomes' => '["Elimu ya kujenga stadi za uhasibu na usimamizi wa fedha","kuzilinda rasilimali za taasisi kwa kuweka taarifa sahihi na kufanya maamuzi sahihi kwa lengo la kufanikisha madhumuni ya taasisi."]',
                'language' => NULL,
            'summary' => '<p>Moduli hii imeaandaliwa kwa lengo kuu la kujenga weledi (ufahamu) katika stadi za uhasibu na usimamizi wa fedha kwa watendaji na viongozi wa taasisi. Kwa kuwa taaluma ni pana sana ya maswala ya uhasibu na usimamizi wa fedha, mdouli hii imelenga katika kutoa mwangaza wa kumfanya kiongozi na mtendaji katika taasisi kutekeleza wajibu wao kwa mambo muhimu lakini bila kupoteza rasilimali za taasisi.</p>',
                'duration' => '3',
                'name' => 'STADI ZAUHASIBU NA USIMAMIZI WA FEDHA',
            'description' => '<p>Moduli hii imeaandaliwa kwa lengo kuu la kujenga weledi (ufahamu) katika stadi za uhasibu na usimamizi wa fedha kwa watendaji na viongozi wa taasisi. Kwa kuwa taaluma ni pana sana ya maswala ya uhasibu na usimamizi wa fedha, mdouli hii imelenga katika kutoa mwangaza wa kumfanya kiongozi na mtendaji katika taasisi kutekeleza wajibu wao kwa mambo muhimu lakini bila kupoteza rasilimali za taasisi.</p>',
                'image' => 'media/BIP4BYmMCzB46TEa5F9cRRSN8PRZdj8NHNx6dkrx.png',
                'video' => NULL,
                'certificate' => 'Yes',
                'status' => 'Published',
                'level' => 'Beginner',
                'created_at' => '2022-09-27 10:17:59',
                'updated_at' => '2022-09-27 13:33:01',
                'slug' => 'stadi-zauhasibu-na-usimamizi-wa-fedha',
            ),
            5 => 
            array (
                'id' => '8',
                'uuid' => 'e5f1d50d-6b62-414a-bc20-fcad7bf5f733',
                'workspace_id' => '1',
                'admin_id' => '1',
                'category_id' => '6',
                'price' => '15000.00',
                'price_monthly' => NULL,
                'price_yearly' => NULL,
                'price_two_years' => NULL,
                'price_three_years' => NULL,
                'deadline' => '2022-09-27',
                'outcomes' => '["Kutafuta elimu\\/ ujuzi ni wajibu kwa Waislamu wote, wanaume na wanawake."]',
                'language' => NULL,
                'summary' => '<p>Kutokana na dunia ya sasa mambo mengi kuhitaji maarifa, inatubidi tujifunze kila mara ili tuweze kuendelea kumcha Mwenyezi Mungu wa pekee, aliyetakasika na wakati huo huo tukimudu maisha yenye mabadiliko.</p>',
                'duration' => '1',
                'name' => 'STADI ZA MAISHA KWA MWANAMKE WA KIISLAM',
                'description' => '<p>Kutokana na dunia ya sasa mambo mengi kuhitaji maarifa, inatubidi tujifunze kila mara ili tuweze kuendelea kumcha Mwenyezi Mungu wa pekee, aliyetakasika na wakati huo huo tukimudu maisha yenye mabadiliko.</p>',
                'image' => 'media/bcOYOxA5bvznevQV4ZFbNHbskj9zIheCaTd2GhlS.png',
                'video' => NULL,
                'certificate' => 'Yes',
                'status' => 'Published',
                'level' => 'Beginner',
                'created_at' => '2022-09-27 10:31:13',
                'updated_at' => '2022-09-27 13:53:59',
                'slug' => 'stadi-za-maisha-kwa-mwanamke-wa-kiislam',
            ),
            6 => 
            array (
                'id' => '9',
                'uuid' => 'e91a9949-b0a3-4ed9-a82b-94283f736c76',
                'workspace_id' => '1',
                'admin_id' => '1',
                'category_id' => '6',
                'price' => '20000.00',
                'price_monthly' => NULL,
                'price_yearly' => NULL,
                'price_two_years' => NULL,
                'price_three_years' => NULL,
                'deadline' => '2022-09-27',
                'outcomes' => '["Maana ya ufundishaji","Kutambua kila njia ya kufundisha kwa faida zake na hasara zake."]',
                'language' => NULL,
            'summary' => '<p>Ufundishaji (ualimu) ni fani ambayo kila mjuzii wa kitu chochote lazima kuna chanzo na njia zilizo tumika kumfanya awe mjuzi. Na kila mjuzi ana mjuzi wake. Hivyo katika kozi hii kila aliye mjuzi ni wajibu kwake kuwajuza wengine wasio na ujuzi kupitia njia zilizo bainishwa na huo ndio ufundishaji. </p>',
                'duration' => '2',
                'name' => 'KOZI YA WALIMU WA MADRASA MBINU ZA UFUNDISHAJI',
            'description' => '<p>Ufundishaji (ualimu) ni fani ambayo kila mjuzii wa kitu chochote lazima kuna chanzo na njia zilizo tumika kumfanya awe mjuzi. Na kila mjuzi ana mjuzi wake. Hivyo katika kozi hii kila aliye mjuzi ni wajibu kwake kuwajuza wengine wasio na ujuzi kupitia njia zilizo bainishwa na huo ndio ufundishaji. </p>',
                'image' => 'media/5O73D8NtiwVQ5J66TzFXDSV9cVUtVZA9YryDSfOV.png',
                'video' => NULL,
                'certificate' => 'Yes',
                'status' => 'Published',
                'level' => 'Beginner',
                'created_at' => '2022-09-27 10:41:00',
                'updated_at' => '2022-09-27 13:54:33',
                'slug' => 'kozi-ya-walimu-wa-madrasa-mbinu-za-ufundishaji',
            ),
            7 => 
            array (
                'id' => '10',
                'uuid' => '92c52704-bfff-4a2c-a31c-6711dc34cf19',
                'workspace_id' => '1',
                'admin_id' => '1',
                'category_id' => '3',
                'price' => NULL,
                'price_monthly' => NULL,
                'price_yearly' => NULL,
                'price_two_years' => NULL,
                'price_three_years' => NULL,
                'deadline' => '2022-09-27',
                'outcomes' => '["Kuelewa maana ya Uchumi na Ujasiriamali.","Kuelewa dhana halisi ya ujasiriamali na kujenga stadi za utendaji halisi.","Kujua fursa za kushiriki shughuli za kujenga uchumi."]',
                'language' => NULL,
            'summary' => '<p>Moduli hii inahusu UCHUMI NA UJASIRIAMALI imekusudia kuwajengea uwezo Waisilam kwa ujumla wao (viongozi na waisiokuwa viongozi) maarifa muhimu yanahusu UCHUMI na UJASIRIAMALI ili waweze kuingia vyema katika kuujenga uchumi wa mtu mmoja mmoja na jamii kwa ujumla kwa kufanya shughuli za ujasiriamali au kwa wale ambao tayari wanafanya shughuli za ujasiriamali waweze kuongeza maarifa yao na kupiga hatua zaidi za kiuchumi.</p>',
                'duration' => NULL,
                'name' => 'KOZI YA UCHUMI NA UJASILIA MALI',
            'description' => '<p>Moduli hii inahusu UCHUMI NA UJASIRIAMALI imekusudia kuwajengea uwezo Waisilam kwa ujumla wao (viongozi na waisiokuwa viongozi) maarifa muhimu yanahusu UCHUMI na UJASIRIAMALI ili waweze kuingia vyema katika kuujenga uchumi wa mtu mmoja mmoja na jamii kwa ujumla kwa kufanya shughuli za ujasiriamali au kwa wale ambao tayari wanafanya shughuli za ujasiriamali waweze kuongeza maarifa yao na kupiga hatua zaidi za kiuchumi.</p>',
                'image' => 'media/sbUjRJToZuI4gPzZUlj8mzPoBGaBFIWLNGm90tR0.png',
                'video' => NULL,
                'certificate' => 'Yes',
                'status' => 'Draft',
                'level' => 'Beginner',
                'created_at' => '2022-09-27 11:41:16',
                'updated_at' => '2022-09-27 11:41:16',
                'slug' => 'kozi-ya-uchumi-na-ujasilia-mali',
            ),
            8 => 
            array (
                'id' => '11',
                'uuid' => '07ba55e7-f3e1-4d10-bc75-f777ca827e36',
                'workspace_id' => '1',
                'admin_id' => '1',
                'category_id' => '3',
                'price' => '20000.00',
                'price_monthly' => NULL,
                'price_yearly' => NULL,
                'price_two_years' => NULL,
                'price_three_years' => NULL,
                'deadline' => '2022-09-27',
                'outcomes' => '["kanuni za kukusanya na kusambaza habari"]',
                'language' => NULL,
            'summary' => '<p>Uandishi wa habari (kwa Kiingereza journalism) ni kazi ya kukusanya, kupanga na kusambaza habari kwa wasomaji, wasikilizaji na watazamaji katika jamii. </p>',
                'duration' => '3',
                'name' => 'KOZI YA UANDSIHI WA HABARI',
            'description' => '<p>Uandishi wa habari (kwa Kiingereza journalism) ni kazi ya kukusanya, kupanga na kusambaza habari kwa wasomaji, wasikilizaji na watazamaji katika jamii. </p>',
                'image' => 'media/g07Y4X49mHMy8XkuR3PWrME0CHcogep0hxXHxwUA.png',
                'video' => NULL,
                'certificate' => 'Yes',
                'status' => 'Published',
                'level' => 'Beginner',
                'created_at' => '2022-09-27 11:52:24',
                'updated_at' => '2022-09-27 13:51:17',
                'slug' => 'kozi-ya-uandsihi-wa-habari',
            ),
            9 => 
            array (
                'id' => '12',
                'uuid' => '1f2efbea-d282-496a-83ef-70b5c23ee2c5',
                'workspace_id' => '1',
                'admin_id' => '1',
                'category_id' => '5',
                'price' => '60000.00',
                'price_monthly' => NULL,
                'price_yearly' => NULL,
                'price_two_years' => NULL,
                'price_three_years' => NULL,
                'deadline' => '2022-09-27',
                'outcomes' => '["Kusoma, kuandika na kuzungumza Kiarabu."]',
                'language' => NULL,
                'summary' => '<p>Kiarabu ni chanzo cha mafunzo ya uislam kwani vitabu vya kale vimeandikwa kwa kiarabu na mtume Muhammad Rehema za Allah aliyetakasika alikuwa mwarabu na aliyeongea kiarabu. Uislam ni dini ya ulimwengu na Qur’an imenakiliwa katika kiarabu na tafsiri zake zinatokana na kiarabu. Kwa hiyo utaona kiarabu ni Lugha muhimu kwa waislamu wote ili waweze kujua dini vizuri bila kuegemea tafsiri tu.</p>',
                'duration' => '6',
                'name' => 'KOZI YA LUGHA YA KIARABU',
                'description' => '<p>Kiarabu ni chanzo cha mafunzo ya uislam kwani vitabu vya kale vimeandikwa kwa kiarabu na mtume Muhammad Rehema za Allah aliyetakasika alikuwa mwarabu na aliyeongea kiarabu. Uislam ni dini ya ulimwengu na Qur’an imenakiliwa katika kiarabu na tafsiri zake zinatokana na kiarabu. Kwa hiyo utaona kiarabu ni Lugha muhimu kwa waislamu wote ili waweze kujua dini vizuri bila kuegemea tafsiri tu.</p>',
                'image' => 'media/H5IJ05f4Mr9D6YF7ilIFvVOFTiiw6igZ3cAtR6zU.png',
                'video' => NULL,
                'certificate' => 'Yes',
                'status' => 'Published',
                'level' => 'Beginner',
                'created_at' => '2022-09-27 12:04:31',
                'updated_at' => '2022-09-27 13:32:28',
                'slug' => 'kozi-ya-lugha-ya-kiarabu',
            ),
            10 => 
            array (
                'id' => '13',
                'uuid' => 'bb3b6261-c413-4b56-8231-71ab2301b3ea',
                'workspace_id' => '1',
                'admin_id' => '1',
                'category_id' => '6',
                'price' => '100000.00',
                'price_monthly' => NULL,
                'price_yearly' => NULL,
                'price_two_years' => NULL,
                'price_three_years' => NULL,
                'deadline' => '2022-09-27',
                'outcomes' => '["Planning, organizing, staffing, leading or directing, and controlling an educational institution."]',
                'language' => NULL,
                'summary' => '<p>School Management comprises planning, organizing, staffing, leading or directing, and controlling an educational institution with the purpose of accomplishing the educational goals. Its main aim is to create a safe and conducive learning environment in the school.</p>',
                'duration' => '3',
                'name' => 'SCHOOL MANAGEMENT COURSE',
                'description' => '<p>School Management comprises planning, organizing, staffing, leading or directing, and controlling an educational institution with the purpose of accomplishing the educational goals. Its main aim is to create a safe and conducive learning environment in the school.</p>',
                'image' => 'media/l5eGGmSkEcVKDUH9sxYCpxLwim3Leo91VUJqqhb4.png',
                'video' => NULL,
                'certificate' => 'Yes',
                'status' => 'Published',
                'level' => 'Beginner',
                'created_at' => '2022-09-27 12:14:53',
                'updated_at' => '2022-09-27 12:20:08',
                'slug' => 'school-management-course',
            ),
        ));
        
        
    }
}